---
- name: Reload sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl -p /etc/sysctl.conf
  register: my_sysctl
  changed_when: my_sysctl.rc != 0
